apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-load
  template:
    metadata:
      labels:
        app: memory-load
    spec:
      containers:
      - name: memory-load-container
        image: python:3.11-alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        command: ["python", "-c"]
        args:
          - |
            import time
            data = []
            while True:
                data.extend([0]*10**6)
                if len(data) > 50*10**6:
                    data = []
                time.sleep(2)
